#!/bin/bash
set -e

# Voice Call Report Generator
# Usage: ./generate_report.sh CALL_SID

# Find the datastore container dynamically
DATASTORE_CONTAINER=$(docker ps --format "{{.Names}}" | grep -E "codel.*datastore" | grep -v mocked | grep -v smoke | head -1)
if [ -z "$DATASTORE_CONTAINER" ]; then
    echo "Error: Could not find datastore container"
    echo "Available containers:"
    docker ps --format "{{.Names}}" | grep datastore
    exit 1
fi

CALL_SID="${1:-}"

if [ -z "$CALL_SID" ]; then
    echo "Usage: $0 CALL_SID"
    echo ""
    echo "Recent calls:"
    docker exec -i "$DATASTORE_CONTAINER" psql -U codel -d codel -t <<'EOF'
SELECT
    m.provider_data->>'call_sid' as call_sid,
    TO_CHAR(MIN(m.created_at), 'YYYY-MM-DD HH24:MI') as started
FROM message m
WHERE m.provider_data->>'type' = 'voice_transcript'
  AND m.provider_data->>'call_sid' IS NOT NULL
GROUP BY m.provider_data->>'call_sid'
ORDER BY MIN(m.created_at) DESC
LIMIT 5;
EOF
    exit 1
fi

# Create output directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/tmp/reports"
mkdir -p "$OUTPUT_DIR"

OUTPUT_FILE="$OUTPUT_DIR/voice_call_${CALL_SID}.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Generate report
docker exec -i "$DATASTORE_CONTAINER" psql -U codel -d codel -t -A -F'|' <<EOF | python3 -c "
import sys
from datetime import datetime

print('# Voice Call Report')
print('')
print('**Call SID:** $CALL_SID')
print('**Generated:** $TIMESTAMP')
print('')
print('## Score Trajectory')
print('')
print('| Seg | Speaker | Conflict Health | Score | Delta | Impact | Transcript |')
print('|-----|---------|-----------------|-------|-------|--------|------------|')

prev_score = None
first_score = None
last_score = None
max_delta = 0
max_delta_seg = None
min_delta = 0
min_delta_seg = None

rows = []
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    parts = line.split('|')
    if len(parts) >= 5:
        seg = parts[0].strip()
        speaker = parts[1].strip() or 'Unknown'
        conflict = parts[2].strip() or '-'
        score_str = parts[3].strip()
        transcript = parts[4].strip()[:80] if len(parts) > 4 else ''

        # Parse score
        try:
            score = int(score_str) if score_str and score_str != '-' else None
        except:
            score = None

        # Calculate delta
        if score is not None:
            if first_score is None:
                first_score = score
            last_score = score

            if prev_score is not None:
                delta = score - prev_score
                delta_str = '+{}'.format(delta) if delta >= 0 else str(delta)

                # Track max/min delta
                if delta > max_delta:
                    max_delta = delta
                    max_delta_seg = seg
                if delta < min_delta:
                    min_delta = delta
                    min_delta_seg = seg

                # Impact indicator
                if delta > 10:
                    impact = 'Very Positive'
                elif delta > 0:
                    impact = 'Positive'
                elif delta == 0:
                    impact = 'Neutral'
                elif delta > -10:
                    impact = 'Negative'
                else:
                    impact = 'Very Negative'
            else:
                delta_str = '--'
                impact = 'Start'
            prev_score = score
            score_display = str(score)
        else:
            delta_str = '-'
            score_display = '-'
            impact = 'N/A'

        # Escape pipes in transcript
        transcript = transcript.replace('|', '\\|')

        print('| {} | {} | {} | {} | {} | {} | {} |'.format(
            seg, speaker, conflict, score_display, delta_str, impact, transcript
        ))
        rows.append((seg, speaker, conflict, score_display, delta_str, impact, transcript))

print('')
print('## Summary')
print('')
if first_score is not None and last_score is not None:
    total_change = last_score - first_score
    change_str = '+{}'.format(total_change) if total_change >= 0 else str(total_change)
    print('- **Starting Score:** {}'.format(first_score))
    print('- **Final Score:** {}'.format(last_score))
    print('- **Total Change:** {}'.format(change_str))
    if max_delta_seg:
        print('- **Most Positive Impact:** Segment {} (+{})'.format(max_delta_seg, max_delta))
    if min_delta_seg:
        print('- **Most Negative Impact:** Segment {} ({})'.format(min_delta_seg, min_delta))
else:
    print('- No scored segments found')

print('')
print('---')
print('*Report generated by voice-call-report skill*')
" > "$OUTPUT_FILE"
SELECT
    (m.provider_data->>'segment_number')::int as seg,
    COALESCE(m.provider_data->>'speaker', 'Unknown') as speaker,
    COALESCE(me.enrichment_data->>'segment_conflict_health', '-') as conflict_health,
    COALESCE((me.enrichment_data->>'call_score')::text, '-') as score,
    m.content as transcript
FROM message m
LEFT JOIN message_enrichment me ON me.message_id = m.id
WHERE m.provider_data->>'call_sid' = '$CALL_SID'
  AND m.provider_data->>'type' = 'voice_transcript'
ORDER BY (m.provider_data->>'segment_number')::int;
EOF

echo "Report saved to: $OUTPUT_FILE"
echo ""
cat "$OUTPUT_FILE"
